/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;





import fileSystem.fileSystem;
import fileSystem.fileSystemException;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JApplet;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import substructure.GUIOutput;





/**
 *
 * @author xoxoxo
 */
public class GUI extends javax.swing.JFrame
{
    private  GUIOutput out =  GUIOutput.getInstance();
    private int ActiveTabIndex              =   0;
    private Explorer explorer;
    private KreisPanel state;
    private JLabel statel;
    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
        owninitComponents();
    }
    
 
    private void owninitComponents()
    {

        //tree.setPreferredSize(new Dimension(300, 150));
        JLabel jLabel1 = new JLabel();
        jLabel1.setText("Offline");
        
        //netstate.add(new JLabel("test<s"));
        //netstate.validate();
        state = new KreisPanel();
        
        state.setBounds(3, 7, 25, 25);
       
        state.setVisible(true);
        add(state);
        
        statel = new JLabel("Offline");
        statel.setBounds(30, 7, 100, 25);
        statel.setVisible(true);
        add(statel);
        
        AdminConfigPanel.setVisible(false);
       // imagetest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hdd.jpeg")));
        //imagetest.setText("");
        
       
       
       
        
        new otherTab(jTabbedPane5);
        
        new Config(jTabbedPane5);
        
         //init ExplorerTab
        explorer = new Explorer(jTabbedPane5);
        
        UIManager.put("nimbusBase", new ColorUIResource(0, 0, 0));
        UIManager.put("textForeground", new ColorUIResource(255, 69, 0));
        
        /*Set Icon Image*/
        /*
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("/substructure/hdd.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        setIconImage(image);
        
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        AdminConfigPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AdminLoginPanel = new javax.swing.JPanel();
        AdminLoginSent = new javax.swing.JButton();
        AdminLoginLabel = new javax.swing.JLabel();
        AdminUsernameField = new javax.swing.JTextField();
        AdminPasswordField = new javax.swing.JPasswordField();
        netstate = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verteiltes Filesystem");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane5MouseClicked(evt);
            }
        });

        jLabel4.setText("jLabel4");

        AdminLoginSent.setText("Anmelden");
        AdminLoginSent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginSentMouseClicked(evt);
            }
        });
        AdminLoginSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginSentActionPerformed(evt);
            }
        });

        AdminLoginLabel.setText("Login:");

        AdminUsernameField.setText("Username");

        AdminPasswordField.setText("Password");

        javax.swing.GroupLayout AdminLoginPanelLayout = new javax.swing.GroupLayout(AdminLoginPanel);
        AdminLoginPanel.setLayout(AdminLoginPanelLayout);
        AdminLoginPanelLayout.setHorizontalGroup(
            AdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminLoginSent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminLoginLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminLoginPanelLayout.setVerticalGroup(
            AdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminLoginLabel)
                .addGap(37, 37, 37)
                .addComponent(AdminUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(AdminLoginSent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminConfigPanelLayout = new javax.swing.GroupLayout(AdminConfigPanel);
        AdminConfigPanel.setLayout(AdminConfigPanelLayout);
        AdminConfigPanelLayout.setHorizontalGroup(
            AdminConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminConfigPanelLayout.createSequentialGroup()
                .addGroup(AdminConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminConfigPanelLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(AdminLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminConfigPanelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminConfigPanelLayout.setVerticalGroup(
            AdminConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminConfigPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(95, 95, 95)
                .addComponent(AdminLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Admin", AdminConfigPanel);

        netstate.setOpaque(false);
        netstate.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout netstateLayout = new javax.swing.GroupLayout(netstate);
        netstate.setLayout(netstateLayout);
        netstateLayout.setHorizontalGroup(
            netstateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        netstateLayout.setVerticalGroup(
            netstateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(netstate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(netstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane5MouseClicked
        // TODO add your handling code here:
        if(!Config.isRootDir()){
            try {
                fileSystem fs = fileSystem.getInstance();
                fs.setnewFileSystem("127.0.0.1", Config.getRootDir());
            } catch (fileSystemException ex) {
                out.print("(GUI-Z227) lokales fileySystem konnte nicht eingelesen werden");
            }
            out.print("(GUI - TabChange) Lokales fileSystem wurde eingelesen");
        }

        ActiveTabIndex = jTabbedPane5.getSelectedIndex();
        out.print("Panel: " + jTabbedPane5.getTitleAt(ActiveTabIndex) + " wurde geöffnet");
       
        
        switch(jTabbedPane5.getTitleAt(ActiveTabIndex))
        {
            case "Config":
            break;
            case "Explorer":   if(!Config.isRootDir()){  explorer.addTab(jTabbedPane5, ActiveTabIndex);}
            break;
                                
           

            

        }
        
        
        
        

    }//GEN-LAST:event_jTabbedPane5MouseClicked

    private void AdminLoginSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginSentActionPerformed
        //Switcht zwischen dem Login und Admin Panel

        if(Admin.Login(AdminUsernameField.getText(), AdminPasswordField.getText()))
        {
            
            AdminLoginPanel.setVisible(false);
            AdminConfigPanel.setVisible(true);
        }

    }//GEN-LAST:event_AdminLoginSentActionPerformed

    private void AdminLoginSentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginSentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginSentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminConfigPanel;
    private javax.swing.JLabel AdminLoginLabel;
    private javax.swing.JPanel AdminLoginPanel;
    private javax.swing.JButton AdminLoginSent;
    private javax.swing.JPasswordField AdminPasswordField;
    private javax.swing.JTextField AdminUsernameField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JPanel netstate;
    // End of variables declaration//GEN-END:variables
    
    class KreisPanel extends JPanel{
        
        Graphics2D g2;
        Color color = Color.RED;
        
        @Override
        public void paint(Graphics g) {
             g2 = (Graphics2D) g;

            g2.setPaint(color);
            g2.fill(new Ellipse2D.Double(0, 0, 24, 24));

            
        }
        
        public void setRed()
        {
            this.color = Color.RED;
            repaint();
        }
        
        public void setGreen()
        {
            this.color = Color.GREEN;
            repaint();
        }
    } 
  
}
